# Generated by Django 3.1.5 on 2021-01-30 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_book', '0002_auto_20210130_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_saled', to=settings.AUTH_USER_MODEL),
        ),
    ]
